image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - pages

build_and_push:
  services:
    - docker:dind
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - Dockerfile
        - .gitlab-ci.yml

pages:
  stage: pages
  image:
    name: $CI_REGISTRY_IMAGE:latest
  script:
    - bash gen_html.sh
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - Dockerfile
        - .gitlab-ci.yml
        - '**/*.archimate'
  artifacts:
    name: "$CI_JOB_NAME from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    expire_in: 30d
    paths:
      - public

